services:
  database:
    image: "postgres:16"
    env_file:
      - .env.docker
    networks:
      - legisdata

  caddy:
    image: 'caddy:2'
    volumes:
      - ./podman/caddy/etc/caddy:/etc/caddy
      - ./podman/caddy/data:/data
    ports:
      - 0.0.0.0:8080:8080
    env_file:
      - .env.docker
    networks:
      - legisdata

  backend:
    build:
      context: .
      name: legisdata_backend
      no_cache: true
      pull: true
    env_file:
      - .env.docker
    networks:
      - legisdata

networks:
  legisdata: