name: image builder
run-name: Building new docker containers
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set lower case owner name
        run: echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Set current date as env variable
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y podman
      - run: podman build --tag "$OWNER_LC/legisdata-frontend:$TODAY" -f ./podman/frontend/Dockerfile .
      - run: podman build --tag "$OWNER_LC/legisdata-backend:$TODAY" -f ./podman/backend/Dockerfile .
      - run: echo ${{ secrets.GITHUB_TOKEN }} | podman login ghcr.io -u ${{ github.repository_owner }} --password-stdin