name: image builder
run-name: Building new docker containers
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y podman
      - run: podman build --tag legisdata_frontend -f ./podman/frontend/Dockerfile .