name: image builder
run-name: Building new docker containers
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set lower case owner name
        run: echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y podman
      - run: echo ${{ secrets.GITHUB_TOKEN }} | podman login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - run: podman build --tag "ghcr.io/$OWNER_LC/legisdata-frontend:latest" -f ./podman/frontend/Dockerfile .
      - run: podman build --tag "ghcr.io/$OWNER_LC/legisdata-backend:latest" -f ./podman/backend/Dockerfile .
      - run: podman push "ghcr.io/$OWNER_LC/legisdata-frontend:latest"
      - run: podman push "ghcr.io/$OWNER_LC/legisdata-backend:latest"